# Generated by Django 2.0.5 on 2018-05-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('stok', models.CharField(blank=True, max_length=50, verbose_name='номер')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='№')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='цена')),
                ('invoce_doc', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculation.Invoice', verbose_name='документ')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('name', models.TextField(verbose_name='название')),
                ('source', models.CharField(blank=True, max_length=250, verbose_name='номер')),
                ('technology', models.TextField(verbose_name='технология приготовления')),
            ],
        ),
        migrations.CreateModel(
            name='MapItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='№')),
                ('brutto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='брутто')),
                ('netto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='неттто')),
                ('map_doc', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculation.Map', verbose_name='документ')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name=' Имя')),
                ('second_name', models.CharField(max_length=100, verbose_name=' Отчество')),
                ('last_name', models.CharField(max_length=100, verbose_name=' Фамилия')),
            ],
            options={
                'verbose_name_plural': 'Физ. лица',
                'ordering': ['last_name', 'first_name', 'last_name'],
                'verbose_name': 'Физ. лица',
                'db_table': 'appcalc_peoples',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=' название')),
            ],
            options={
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
                'verbose_name': 'Продукты',
                'db_table': 'appcalc_products',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='краткое название')),
                ('full_name', models.CharField(max_length=250, verbose_name='полное название')),
                ('code', models.SlugField(max_length=4, unique=True, verbose_name='код')),
            ],
            options={
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['code'],
                'verbose_name': 'Единицы измерения',
                'db_table': 'appcalc_units',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculation.Unit', verbose_name='ед. изм'),
        ),
        migrations.AddField(
            model_name='mapitems',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Product', verbose_name='сырье'),
        ),
        migrations.AddField(
            model_name='map',
            name='agreed',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='agreed', to='calculation.People', verbose_name='согласовано'),
        ),
        migrations.AddField(
            model_name='map',
            name='approved',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='approved', to='calculation.People', verbose_name='утверждено'),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='adopted',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='adopted', to='calculation.People', verbose_name='принял'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivered',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='delivered', to='calculation.People', verbose_name='сдал'),
        ),
    ]
