# Generated by Django 2.0.5 on 2018-05-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сontractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Котрагенты',
                'verbose_name': 'Котрагенты',
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['number', 'created_at'], 'verbose_name': 'Накладные', 'verbose_name_plural': 'Накладные'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['number', 'created_at'], 'verbose_name': 'Технологические карты', 'verbose_name_plural': 'Технологические карты'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='stok',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contractor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Сontractor', verbose_name='товар'),
        ),
    ]
