# Generated by Django 2.0.5 on 2018-05-31 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_auto_20180531_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stoсk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion', models.CharField(choices=[('arr', 'arrival'), ('exp', 'expense')], default='arr', max_length=3)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='количество')),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
            ],
        ),
        migrations.AddField(
            model_name='сontractor',
            name='type_c',
            field=models.CharField(choices=[('in', 'interior'), ('out', 'outer')], default='out', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contractor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Сontractor', verbose_name='Котрагент'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='map',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='map',
            name='source',
            field=models.CharField(blank=True, max_length=250, verbose_name='источник'),
        ),
        migrations.AddField(
            model_name='stoсk',
            name='from_of',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Сontractor', verbose_name='Котрагент'),
        ),
        migrations.AddField(
            model_name='stoсk',
            name='invoce',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Invoice', verbose_name='накладная'),
        ),
        migrations.AddField(
            model_name='stoсk',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Product', verbose_name='товар'),
        ),
    ]
