# Generated by Django 2.0.5 on 2018-05-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_auto_20180531_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stoсk',
            new_name='Stock',
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
    ]
