# Generated by Django 2.0.5 on 2018-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_auto_20180531_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='сумма'),
        ),
    ]
