# Generated by Django 2.0.5 on 2018-06-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0006_auto_20180602_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=250, verbose_name='название'),
        ),
    ]
