# Generated by Django 2.0.5 on 2018-06-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0010_auto_20180603_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculation.Unit', verbose_name='ед. изм'),
        ),
    ]
