# Generated by Django 2.0.5 on 2018-06-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0011_map_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_children', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='создано')),
                ('values', models.TextField(default='gAN9cQAu', verbose_name='')),
                ('food_intake', models.PositiveIntegerField(db_index=True, verbose_name='приём пищи')),
                ('dish', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculation.Dish', verbose_name='блюдо')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='from_of',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='invoce',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateField(db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='motion',
            field=models.SmallIntegerField(choices=[('in', 'interior'), ('out', 'outer')], default=1),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
