# Generated by Django 2.0.5 on 2018-06-05 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0013_auto_20180604_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Product', verbose_name='продукт')),
            ],
            options={
                'ordering': ['product', 'created_at'],
                'verbose_name_plural': 'Регистр цен',
                'db_table': 'calculation_regprice',
                'verbose_name': 'Регистр цен',
            },
        ),
    ]
