# Generated by Django 2.0.5 on 2018-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0014_regprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regprice',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
    ]
