# Generated by Django 2.0.5 on 2018-06-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0016_auto_20180605_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculation.Product', verbose_name='товар'),
        ),
    ]
