# Generated by Django 2.0.5 on 2018-06-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0017_dish_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='menu',
        ),
        migrations.AddField(
            model_name='invoice',
            name='motion',
            field=models.SmallIntegerField(choices=[('in', 'interior'), ('out', 'outer')], default=1),
        ),
    ]
