# Generated by Django 2.0.5 on 2018-06-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0018_auto_20180606_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['product', 'created_at'], 'verbose_name': 'Запись регистра "Cклад"', 'verbose_name_plural': 'Регистр "Cклад"'},
        ),
        migrations.AlterModelOptions(
            name='regprice',
            options={'ordering': ['product', 'created_at'], 'verbose_name': 'Запись регистра "Цены"', 'verbose_name_plural': 'Регистр "Цены"'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='motion',
            field=models.SmallIntegerField(choices=[(1, 'приход'), (-1, 'расход')], default=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='motion',
            field=models.SmallIntegerField(choices=[(1, 'приход'), (-1, 'расход')], default=1),
        ),
        migrations.AlterField(
            model_name='сontractor',
            name='type_c',
            field=models.CharField(choices=[('in', 'внутренний'), ('out', 'внешний')], default='out', max_length=3),
        ),
    ]
