# Generated by Django 2.0.5 on 2018-06-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0019_auto_20180606_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='regprice',
            name='invoce',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculation.Invoice', verbose_name='накладная'),
        ),
    ]
