# Generated by Django 2.0.5 on 2018-06-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0020_regprice_invoce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(db_index=True, verbose_name='создано'),
        ),
    ]
