# Generated by Django 2.0.5 on 2018-06-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0021_auto_20180606_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('type_c', models.CharField(choices=[('in', 'внутренний'), ('out', 'внешний')], default='out', max_length=3, verbose_name='Тип')),
            ],
            options={
                'verbose_name_plural': 'Котрагенты',
                'ordering': ['name'],
                'verbose_name': 'Котрагенты',
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contractor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Contractor', verbose_name='Котрагент'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, help_text='Номер накладной', max_length=50, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='from_of',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Contractor', verbose_name='Котрагент'),
        ),
        migrations.DeleteModel(
            name='Сontractor',
        ),
    ]
