# Generated by Django 2.0.5 on 2018-06-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0022_auto_20180613_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='type_c',
            field=models.CharField(choices=[('внутренний', 'внутренний'), ('внешний', 'внешний')], default='внешний', max_length=25, verbose_name='Тип'),
        ),
    ]
