# Generated by Django 2.0.5 on 2018-06-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0023_auto_20180613_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='approved',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_approved', to='calculation.People', verbose_name='утверждено'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_intake',
            field=models.PositiveIntegerField(choices=[(1, 'Завтрак'), (2, 'Обед'), (3, 'Полдник'), (4, '1-й ужин'), (5, '2-й ужин')], db_index=True, default=1, verbose_name='приём пищи'),
        ),
    ]
