# Generated by Django 2.0.5 on 2018-06-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0024_auto_20180614_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='adopted',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adopted', to='calculation.People', verbose_name='принял'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contractor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculation.Contractor', verbose_name='Котрагент'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivered',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered', to='calculation.People', verbose_name='сдал'),
        ),
    ]
