# Generated by Django 2.0.5 on 2018-06-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0026_auto_20180618_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('number', 'created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='people',
            unique_together={('last_name', 'first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
    ]
