# Generated by Django 2.0.5 on 2018-06-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0027_auto_20180619_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapitems',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Dish', verbose_name='сырье'),
        ),
        migrations.AlterUniqueTogether(
            name='regprice',
            unique_together={('product', 'created_at')},
        ),
    ]
