# Generated by Django 2.0.5 on 2018-06-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0028_auto_20180621_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapitems',
            name='brutto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='брутто'),
        ),
        migrations.AlterField(
            model_name='mapitems',
            name='netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='неттто'),
        ),
    ]
