# Generated by Django 2.0.5 on 2018-06-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0030_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, null=True, verbose_name='вес в килограммах                                                 одной единицы'),
        ),
    ]
