# Generated by Django 2.0.5 on 2018-06-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0031_auto_20180626_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='dish',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='calculation.Dish', verbose_name='продукт'),
        ),
    ]
