# Generated by Django 2.0.5 on 2018-06-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0032_auto_20180626_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15, null=True, verbose_name='вес в килограммах одной единицы'),
        ),
    ]
