# Generated by Django 2.0.5 on 2018-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0033_auto_20180626_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapitems',
            name='netto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='неттто'),
        ),
    ]
