# Generated by Django 2.0.5 on 2018-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0034_auto_20180626_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='source',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='источник'),
        ),
    ]
