# Generated by Django 2.0.5 on 2018-06-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0035_auto_20180626_2005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regprice',
            unique_together={('product', 'invoce')},
        ),
    ]
