# Generated by Django 2.0.5 on 2018-06-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0036_auto_20180627_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='regprice',
            name='dish',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Dish', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='regprice',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='calculation.Product', verbose_name='номенклатура'),
        ),
    ]
