# Generated by Django 2.0.5 on 2018-06-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0037_auto_20180627_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
    ]
