# Generated by Django 2.0.5 on 2018-06-28 08:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0038_auto_20180628_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='выход порции')),
                ('dish', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='menu_dish', to='calculation.Dish', verbose_name='блюдо')),
            ],
            options={
                'ordering': ['invoce_doc', 'dish'],
                'verbose_name': 'комплектующие меню',
                'verbose_name_plural': 'комплектующие меню',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='out',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='invoce_doc',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculation.Menu', verbose_name='меню'),
        ),
    ]
