# Generated by Django 2.0.5 on 2018-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0039_auto_20180628_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_intake',
            field=models.PositiveIntegerField(choices=[(1, 'Завтрак'), (2, 'Обед'), (3, 'Полдник'), (4, 'ужин 1-й '), (5, 'ужин 2-й')], db_index=True, default=1, verbose_name='приём пищи'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateField(db_index=True, verbose_name='создано'),
        ),
    ]
