# Generated by Django 2.0.5 on 2018-07-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0040_auto_20180723_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='metka',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metka', to='calculation.Invoice', verbose_name='метка'),
        ),
    ]
