# Generated by Django 2.0.5 on 2018-08-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0047_registration_dish'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='map',
            unique_together=set(),
        ),
    ]
