# Generated by Django 2.0.5 on 2019-05-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0048_auto_20180807_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together=set(),
        ),
    ]
