# Generated by Django 2.0.5 on 2019-06-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0050_auto_20190619_0734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regprice',
            unique_together=set(),
        ),
    ]
